// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ45Kd-79WJtA5MQrfZBK5nlCHEXh2Bi4',
    appId: '1:131356970363:web:0ae462908a875ba87ec1de',
    messagingSenderId: '131356970363',
    projectId: 'cool-project-flutter',
    authDomain: 'cool-project-flutter.firebaseapp.com',
    databaseURL: 'https://cool-project-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cool-project-flutter.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu_adahDsRrLrvqb6wcbdh2MNWXK1hu_Q',
    appId: '1:131356970363:android:80fa763d438041d27ec1de',
    messagingSenderId: '131356970363',
    projectId: 'cool-project-flutter',
    databaseURL: 'https://cool-project-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cool-project-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtyMbRpnBjGaJRfXElu2SYrkP3ZAsTkP0',
    appId: '1:131356970363:ios:3b9c007954979a107ec1de',
    messagingSenderId: '131356970363',
    projectId: 'cool-project-flutter',
    databaseURL: 'https://cool-project-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cool-project-flutter.firebasestorage.app',
    iosBundleId: 'com.example.ticketApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtyMbRpnBjGaJRfXElu2SYrkP3ZAsTkP0',
    appId: '1:131356970363:ios:3b9c007954979a107ec1de',
    messagingSenderId: '131356970363',
    projectId: 'cool-project-flutter',
    databaseURL: 'https://cool-project-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cool-project-flutter.firebasestorage.app',
    iosBundleId: 'com.example.ticketApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ45Kd-79WJtA5MQrfZBK5nlCHEXh2Bi4',
    appId: '1:131356970363:web:e5d3402073ce3acb7ec1de',
    messagingSenderId: '131356970363',
    projectId: 'cool-project-flutter',
    authDomain: 'cool-project-flutter.firebaseapp.com',
    databaseURL: 'https://cool-project-flutter-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'cool-project-flutter.firebasestorage.app',
  );
}
